### ISSUE TITLE
Acceptance Testing: 2.2 Adding a person example is not working

### ISSUE THREAD

**Issue by royceljh** [CS2103AUG2017-F11-B2/main#105]
"add n/Betsy Crowe t/friend e/betsycrowe@example.com e/betsy@workemail.com a/Newgate Prison p/1234567 t/criminal w/google.com" this command is not working 

Result message: "Hi, only valid facebook, instagram, linkedin or twitter links will be accepted:)"

Should update the user guide example accordingly.

**Comment by bladerail** [comment]
Thanks for informing!
