### ISSUE TITLE
Acceptance Testing: Profile Edit always returns default entries instead of selected person info

### ISSUE THREAD

**Issue by RSJunior37** [CS2103AUG2017-F11-B2/main#106]
![image](https://user-images.githubusercontent.com/31032660/32362941-140abea0-c0b0-11e7-9203-77c097856285.png)

**Comment by bladerail** [comment]
Sorry, could you elaborate on this? The User Profile is the user's contact, it is not for the selected persons in the addressbook. We are setting this up for a "share" function later on.
