### ISSUE TITLE
Acceptance Testing: sort message to user

### ISSUE THREAD

**Issue by royceljh** [CS2103AUG2017-F11-B2/main#107]
Parameters: sort [name/email/phone/address/tag]

Tag is not a valid parameter for sort
<img width="1421" alt="screen shot 2017-11-03 at 3 01 08 pm" src="https://user-images.githubusercontent.com/31101523/32362976-e0f92a86-c0a7-11e7-947f-e50392f616d3.png">

**Comment by bladerail** [comment]
PS, that's not implemented, will remove.
