### ISSUE TITLE
Acceptance Testing: Userguide documentation of command does not match actual

### ISSUE THREAD

**Issue by RSJunior37** [CS2103AUG2017-F11-B2/main#108]
![image](https://user-images.githubusercontent.com/31032660/32363036-90a17dc8-c0b0-11e7-8ec4-ea4cf9fb9821.png)
![image](https://user-images.githubusercontent.com/31032660/32363043-99e91e68-c0b0-11e7-8aa6-19e01a72b592.png)

**Comment by bladerail** [comment]
Thanks for informing!

**Comment by hansiang93** [comment]
Fixed in [#130](https://github.com/CS2103AUG2017-F11-B2/main/pull/130)
