### ISSUE TITLE
Acceptance Testing: Suggested search does not seem to match partial keywords

### ISSUE THREAD

**Issue by RSJunior37** [CS2103AUG2017-F11-B2/main#109]
![image](https://user-images.githubusercontent.com/31032660/32363109-f4eae314-c0b0-11e7-8bdd-a825cacdc2e9.png)

**Comment by bladerail** [comment]
Will try to change. Thanks for informing!

**Comment by hansiang93** [comment]
Fixed in [#140](https://github.com/CS2103AUG2017-F11-B2/main/pull/140)
