### ISSUE TITLE
Acceptance Testing: Edit command example not working

### ISSUE THREAD

**Issue by royceljh** [CS2103AUG2017-F11-B2/main#110]
The "clearTag/" prefix is not a valid prefix

<img width="1231" alt="screen shot 2017-11-03 at 3 07 00 pm" src="https://user-images.githubusercontent.com/31101523/32363289-92c98890-c0a9-11e7-9dbc-4831f8ff8024.png">

**Comment by bladerail** [comment]
Apologies, sort does not work for tag. Will update accordingly. Thanks for informing!
