### ISSUE TITLE
Acceptance Testing: "Search" text on button is truncated when on focus

### ISSUE THREAD

**Issue by RSJunior37** [CS2103AUG2017-F11-B2/main#112]
![image](https://user-images.githubusercontent.com/31032660/32363251-ba41295c-c0b1-11e7-927d-1c31421c42e0.png)

**Comment by bladerail** [comment]
Thanks for informing!

**Comment by hansiang93** [comment]
Fixed in [#140](https://github.com/CS2103AUG2017-F11-B2/main/pull/140)
