### ISSUE TITLE
Acceptance Testing: Unable to use l alias for list command

### ISSUE THREAD

**Issue by ktnc985** [CS2103AUG2017-F11-B2/main#115]
Unable to use `l` alias for `list` command due to the suggestions box. When enter is pressed it becomes the first item in the suggestion box.

![image](https://user-images.githubusercontent.com/13115806/32363372-0c9da1ce-c0aa-11e7-9324-99dcabbc5670.png)

![image](https://user-images.githubusercontent.com/13115806/32363386-1687441a-c0aa-11e7-8b3d-d5688dcc7d1a.png)

**Comment by bladerail** [comment]
Thanks for informing! Will update.

**Comment by hansiang93** [comment]
Fixed in [#140](https://github.com/CS2103AUG2017-F11-B2/main/pull/140)
