### ISSUE TITLE
Everything on track? 

### ISSUE THREAD

**Issue by PierceAndy** [CS2103AUG2017-F11-B2/main#144]
Everything on track to submit tomorrow? Remember to read the [submission instructions + assessment criteria](https://nus-cs2103.github.io/website/admin/index.html#admin-project-v15) carefully and plan to finish submissions at least few hours before the deadline. 

Feel free to approach me if you have any queries or doubts, or if you need some feedback.

All the best 👍

**Comment by hansiang93** [comment]
EVERYTHING'S BURNING DOWN 🔥🔥🔥🔥🔥🔥🔥🔥

**Comment by bladerail** [comment]
Pierce you've got to save us man.

**Comment by AngularJiaSheng** [comment]
All the tests are failing PIERCEEEEEEEEEEEEEEEEEEEEEEEEEEE HOWWWWWWWWWWW

**Comment by hansiang93** [comment]
@PierceAndy NOOOOOO 
![image](https://media.giphy.com/media/2jlDkaipGfgGc/giphy.gif)

**Comment by bladerail** [comment]
@PierceAndy 

`if (date.equals(new Date(13112017)) {
    f11-b2.isDead = true;
};`

**Comment by hansiang93** [comment]
Refactored f11-b2.dead to d11-b2.isDead to better represent the dire situation of the team. @bladerail

**Comment by zhoukai07** [comment]
https://media2.giphy.com/media/l0HlMG1EX2H38cZeE/giphy.gif

**Comment by zhoukai07** [comment]
![photo nov 07 15 07 48](https://media2.giphy.com/media/l0HlMG1EX2H38cZeE/giphy.gif)

**Comment by zhoukai07** [comment]
Everything is going fine...

![giphy-downsized](https://user-images.githubusercontent.com/19451453/32701310-2b375790-c80e-11e7-876d-192bbb149e3d.gif)

**Comment by bladerail** [comment]
Everything is fine

![gif](https://thumbs.gfycat.com/ShinyFixedAmurminnow-size_restricted.gif)

**Comment by PierceAndy** [comment]
AddressBook's original existing features need to be tested, although they're of a lower priority. Don't worry too much if you can't get them right by the deadline. Focus on the more important parts first.

**Comment by bladerail** [comment]
SHIT PIERCE I FORGOT TO ADD YOU INTO THE ADDRESSBOOK IM SORRY

**Comment by hansiang93** [comment]
OH NO.....

**Comment by hansiang93** [comment]
too late. ITS DONE.

**Comment by AngularJiaSheng** [comment]
This mod gave me a PIERCEing headache.... ba dum tss XDXD

**Comment by PierceAndy** [comment]
Good job guys. Don't worry about anything you might have missed. Focus on your upcoming presentation, but don't forget about your other mods too!

**Comment by hansiang93** [comment]
Closed with minimal issues
